### ISSUE TITLE
Fix how the notification icon is being generated 

### ISSUE THREAD

**Issue by ajolipa** [recogito/unnamed-frontend#7]
Currently getting Astro errors `The response has already been sent to the browser and cannot be altered`. Also it should be generated higher up in the component tree so it can be provided as context.

**Comment by rsimon** [comment]
I looked into this, and I've come across the same issue previously. I must admit I don't understand it entirely. But the cause seems to be that you can't access the Astro.request outside of a page component. The Supabase client uses the Astro request to store the session token (as a Cookie), so you can only instantiate the Supabase client in the page.

Now the weird part is: if you import a layout component - like you're doing with the `<DashboardLayout />` - then it looks like it's not possible to use the Astro request in there. The error starts occurring as soon as you try to instantiate the Supabase server client in the `<DashboardLayout />` (or any other layout component). 

In other words: it looks like you can only ever instantiate the supabase client in the page directly, not in the common Layout components (which is pretty unfortunate, since it would be nice to handle these common concerns __only__ in the layout components).

What __does__ seem to be possible, however, is to instantiate the supabase client in the page (as is now done in every page, for the auth check), and then hand it into the layout component as a parameter. Roghly like so:

```
<DashboardLayout supabase={supabase}>
  //...
</DashboadLayout>
```

and in the DashboardLayout, you could access it like so:

```
---

export interface Props {

  supabase: SupabaseClient;

}

const { supabase } = Astro.props;

// And then do whatever you need with supabase
````

I just tested this quickly, and it seems to work.

**Comment by rsimon** [comment]
P.S.: for posterity, the error was introduced in this commit:
https://github.com/recogito/unnamed-frontend/commit/a210fed968d093ec0c797e5eb6e876f38b4a0fe6

And it's exactly this change here where Astro starts acting up:
[src/layouts/dashboard/DashboardLayout.astro](https://github.com/recogito/unnamed-frontend/commit/a210fed968d093ec0c797e5eb6e876f38b4a0fe6#diff-09401fc794d34bd3c04dc3e5f527762e3a69f4708bf4d8ee2c67344d2b7a8ef9)

**Comment by rsimon** [comment]
P.P.S.: the other (and perhaps preferable/easier) alternative, of course, would be to not render the notifications widget on the server, but only on the client.
